Example python wsgi uses correct environment, reports errors.

diff --git a/pre-receive b/pre-receive
--- a/pre-receive
+++ b/pre-receive
@@ -1,13 +1,18 @@
 #!/bin/bash
 # git pre-receive hook to deploy to uwsgi "emperor" mode
 
+# Path to compiled, setuid "vassalconf" program
+VASSALCONF=$HOME/uwsgi-deploy/vassalconf
 
-set -e  # Stop if any command produces non-zero return status
+# Stop if any command produces non-zero return status
+set -e
 
+# Determine project name from bare repo directory basename
 REPO=`pwd`
 PROJECT=`basename "$REPO" .git`
-COMMIT=
 
+# Determine commit from standard input
+COMMIT=
 while read LINE; do
     NEW=`echo $LINE|cut -f2 -d' '`
     REF=`echo $LINE|cut -f3 -d' '`
@@ -17,37 +22,67 @@ while read LINE; do
 done
 
 if [[ "$COMMIT" == "" ]]; then
-    echo No update for master
+    echo No update to master
     exit 0
 fi
 
+# Working dir is named after project and prefix of commit hash.
 WORKDIR=$HOME/$PROJECT-$COMMIT
-
 echo "Checking out $WORKDIR..."
-
 mkdir -p $WORKDIR
 git archive $COMMIT | tar -x -C $WORKDIR
 
+# Change to workdir, but also look for .deploy symlink
 cd $WORKDIR
-source environment.sh
+if [[ -L .deploy ]]; then
+    cd `readlink .deploy`
+fi
+
+# Read environment files, if they exist. First in workdir, then home.
+echo -n > vars-$COMMIT.txt
+
+read_environment_file() {
+    if [[ -r $1 ]]; then
+        echo Reading $1
+        source $1
+        egrep '^export [^= ]+=' $1 | cut -f2 -d' ' | cut -f1 -d= >> vars-$COMMIT.txt
+    fi
+}
+
+read_environment_file `pwd`/environment.sh
+read_environment_file $HOME/environment.sh
+
+# Run setup script
+echo "Running setup..."
 chmod +x ./setup && ./setup
 
-URL=`$HOME/vassalconf test $PROJECT $COMMIT < uwsgi.ini`
+# Augment uwsgi with environment
+echo "Augmenting uwsgi.ini with environment..."
+echo "chdir = $PWD" >> uwsgi.ini
+for x in `sort vars-$COMMIT.txt|uniq`; do
+    echo "env = $x=${!x}" >> uwsgi.ini
+done
+
+# Create a test vassal
+URL=`$VASSALCONF test $PROJECT $COMMIT < uwsgi.ini`
 if [[ "$URL" == "" ]]; then
     exit 1
 fi
 
+# Try to load the ping URL repeatedly
 S=2
 while ! curl -s -f $URL >/dev/null; do
     if [ $S -gt 10 ]; then
         echo "Timeout"
-        $HOME/vassalconf rm $PROJECT $COMMIT
+        $VASSALCONF rm $PROJECT $COMMIT
         exit 1
     fi
     echo "Waiting for test server at $URL"
     sleep $S
-    S=$(($S+1))
+    S=$(($S+1))  # Increase delay
 done
 
-$HOME/vassalconf install $PROJECT $COMMIT < uwsgi.ini
+# Install for good
+echo "Looks good! Installing..."
+$VASSALCONF install $PROJECT $COMMIT < uwsgi.ini
 
